apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-task-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-task
  template:
    metadata:
      labels:
        app: todo-app-task
    spec:
      containers:
      - name: todo-app-task
        image: manassehrandriamitsiry/todo-app-task:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"

